repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-ast
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-json
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: ^reference/.*$
      - id: pretty-format-json
        args:
          - --autofix
        exclude: ^reference/docs/.*$
      - id: trailing-whitespace
        exclude: |
          (?x)(
            README.md|
            ^reference/docs/.*$
          )
      - id: requirements-txt-fixer
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
-   repo: https://github.com/PyCQA/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        language_version: python3.8
        additional_dependencies: [
          '-e', 'git+https://github.com/pycqa/pyflakes@1911c20#egg=pyflakes',
          '-e', 'git+https://github.com/pycqa/pycodestyle@d219c68#egg=pycodestyle',
        ]
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.30.0
  hooks:
    - id: terraform_fmt
