version: '3'

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - network
    command:
      - init.sh

  terminal:
    container_name: terminal
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - network
    command:
      - init-terminal.sh

volumes:
  data01:
    driver: local

networks:
  network:
    driver: bridge
